platform :ios, '8.0'

target 'NoChat-Swift-Example' do
    use_frameworks!
    
    pod 'NoChat'
    pod 'NOCProtoKit', :path => '../'
    pod 'YYText'
    pod 'HPGrowingTextView'
    pod 'Alamofire', '~> 4.7'

end
